#!/usr/bin/env python

import os.path,sys
sys.path.insert(0,os.path.join(os.path.dirname(__file__),'lib'))

from controller import main
import cherrypy

#initial Configuration for Vserver-GUI
config = os.path.join(os.path.dirname(__file__),'vserver-gui.conf')
cherrypy.config.update({ 'tools.staticdir.root' : os.path.dirname(os.path.realpath(__file__)) })                       
cherrypy.config.namespaces('vserver') 


root = main.Root()
root.apa = main.Root()



if __name__ == '__main__':
    cherrypy.quickstart(root, config=config)
else:
    cherrypy.tree.mount(root, config=config)