#!/usr/bin/env python

import os.path,sys
sys.path.insert(0,os.path.join(os.path.dirname(__file__),'lib'))

from model.user import User
from lib import db_engine
from controller import main,user,factory
import cherrypy

#initial Configuration for Vserver-GUI
config = os.path.join(os.path.dirname(__file__),'vserver-gui.conf')
cherrypy.config.update({ 'tools.staticdir.root' : os.path.dirname(os.path.realpath(__file__)) })                       

bram = User('Bramandityo','asdfasdf','bram')
db_engine.session.add(bram)
db_engine.session.commit()


root = main.Controller()
root.user = user.Controller()
root.setting = main.Controller()
root.factory = factory.Controller()



if __name__ == '__main__':
    cherrypy.quickstart(root, config=config)
else:
    cherrypy.tree.mount(root, config=config)
