#!/usr/bin/env python

import lib.cherrypy as cherrypy
import os.path
from controller import main

#initial Configuration for Vserver-GUI
config = os.path.join(os.path.dirname(__file__),'vserver-gui.conf')
cherrypy.config.update({ 'tools.staticdir.root' : os.path.dirname(os.path.realpath(__file__)) })                       


root = main.Root()
root.apa = main.Root()



if __name__ == '__main__':
    cherrypy.quickstart(root, config=config)
else:
    cherrypy.tree.mount(root, config=config)
